name: IP Logger

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install gspread google-auth requests

      - name: Create credentials file and validate (auto-fix)
        run: |
          printf '%s' "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
          python - <<'PY'
          import json,sys
          b = open('credentials.json','rb').read()
          try:
              json.loads(b.decode('utf-8'))
              print('CREDENTIALS_JSON_OK')
              sys.exit(0)
          except Exception as e1:
              t = b.decode('utf-8', errors='replace')
              if t.startswith('"') and t.endswith('"'):
                  t = t[1:-1]
              t2 = t.replace('\\n', '\n').replace('\\t', '\t')
              try:
                  json.loads(t2)
                  open('credentials.json', 'w', encoding='utf-8').write(t2)
                  print('CREDENTIALS_JSON_OK_AFTER_UNESCAPE')
                  sys.exit(0)
              except Exception as e2:
                  print('JSON_PARSE_ERROR:', e1)
                  print('JSON_PARSE_ERROR_AFTER:', e2)
                  sys.exit(2)
          PY

      - name: Run IP update script
        run: python update_ip.py
