name: IP Logger

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install gspread google-auth requests

      - name: Create credentials file and validate aggressive clean
        run: |
          printf '%s' "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
          python - <<'PY'
          import json,sys,re
          # Read raw bytes
          raw = open('credentials.json','rb').read()
          # Decode defensively
          try:
              s = raw.decode('utf-8')
          except:
              s = raw.decode('utf-8', errors='replace')
          # Remove BOM
          if s.startswith('\ufeff'):
              s = s.lstrip('\ufeff')
          # Unwrap one layer of surrounding quotes if present (common paste error)
          if s.startswith('"') and s.endswith('"'):
              s = s[1:-1]
          # Convert literal backslash-n and backslash-t sequences to real newlines/tabs
          s = s.replace('\\n', '\n').replace('\\t', '\t')
          # Trim anything before first { and after last } to isolate JSON object
          first = s.find('{')
          last = s.rfind('}')
          if first != -1 and last != -1 and last >= first:
              s = s[first:last+1]
          # Remove non-printable control characters except newline/tab/CR
          s = re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f]', '', s)
          # Final validation and write
          try:
              json.loads(s)
              with open('credentials.json','w', encoding='utf-8') as f:
                  f.write(s)
              print('CREDENTIALS_JSON_OK')
              sys.exit(0)
          except Exception as e:
              print('JSON_PARSE_ERROR:', e)
              sys.exit(2)
          PY

      - name: Show credentials file info
        run: |
          echo "credentials.json size:"
          ls -la credentials.json || true
          echo "first 5 lines (masked if secret)"
          sed -n '1,5p' credentials.json || true

      - name: Run IP update script
        run: python update_ip.py
