      - name: Create credentials file
        run: |
          printf '%s' "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

      - name: Show file size
        run: |
          ls -la credentials.json

      - name: Validate credentials JSON
        run: |
          python - <<'PY'
          import json,sys
          try:
              json.load(open('credentials.json'))
              print('CREDENTIALS_JSON_OK')
          except Exception as e:
              print('JSON_PARSE_ERROR:', e)
              sys.exit(2)
          PY
