      - name: Create credentials file and validate (auto-fix)
        run: |
          printf '%s' "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
          python - <<'PY'
          import json,sys
          b = open('credentials.json','rb').read()
          try:
              json.loads(b.decode('utf-8'))
              print('CREDENTIALS_JSON_OK')
              sys.exit(0)
          except Exception as e1:
              t = b.decode('utf-8', errors='replace')
              # Remove a single pair of surrounding quotes if present
              if t.startswith('"') and t.endswith('"'):
                  t = t[1:-1]
              # Unescape literal backslash-n and backslash-t sequences into real newlines/tabs
              t2 = t.replace('\\n', '\n').replace('\\t', '\t')
              try:
                  json.loads(t2)
                  open('credentials.json', 'w', encoding='utf-8').write(t2)
                  print('CREDENTIALS_JSON_OK_AFTER_UNESCAPE')
                  sys.exit(0)
              except Exception as e2:
                  print('JSON_PARSE_ERROR:', e1)
                  print('JSON_PARSE_ERROR_AFTER:', e2)
                  sys.exit(2)
          PY
